"""added more cols to user

Revision ID: 1a0ee06dd3c1
Revises: c358e2bfcbf
Create Date: 2014-10-08 15:10:04.112638

"""

# revision identifiers, used by Alembic.
revision = '1a0ee06dd3c1'
down_revision = 'c358e2bfcbf'

from alembic import op
import sqlalchemy as sa


def upgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.add_column(u'user', sa.Column('confirmed_at', sa.DateTime(), nullable=True))
    op.add_column(u'user', sa.Column('current_login_at', sa.DateTime(), nullable=True))
    op.add_column(u'user', sa.Column('current_login_ip', sa.String(length=100), nullable=True))
    op.add_column(u'user', sa.Column('last_login_at', sa.DateTime(), nullable=True))
    op.add_column(u'user', sa.Column('last_login_ip', sa.String(length=100), nullable=True))
    op.add_column(u'user', sa.Column('login_count', sa.Integer(), nullable=True))
    ### end Alembic commands ###


def downgrade():
    ### commands auto generated by Alembic - please adjust! ###
    op.drop_column(u'user', 'login_count')
    op.drop_column(u'user', 'last_login_ip')
    op.drop_column(u'user', 'last_login_at')
    op.drop_column(u'user', 'current_login_ip')
    op.drop_column(u'user', 'current_login_at')
    op.drop_column(u'user', 'confirmed_at')
    ### end Alembic commands ###
